language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"

install:
    - sudo apt-get install libgdal-dev
    - pip install tox-travis python-coveralls

script:
    - tox

matrix:
  allow_failures:
    - env: TOXENV=py35-djangomaster
    - env: TOXENV=py36-djangomaster

after_success:
    coveralls
